### ISSUE TITLE
Firefox in dependency list

### ISSUE THREAD

**Issue by petricm** [DIRACGrid/DIRACOS#148]
```
Found duplicates for libpango-1.0.so.0: ['/tmp/diracos/usr/lib64/libpango-1.0.so.0.2800.1', '/tmp/diracos/usr/lib64/firefox/bundled/lib64/libpango-1.0.so.0.4000.4']
Traceback (most recent call last):
  File "/tmp/set_RPATH.py", line 176, in <module>
    main(sys.argv[1])
  File "/tmp/set_RPATH.py", line 171, in main
    check_duplicates(so_names)
  File "/tmp/set_RPATH.py", line 98, in check_duplicates
    raise NotImplementedError(v, hashes)
NotImplementedError: (['/tmp/diracos/usr/lib64/libpango-1.0.so.0.2800.1', '/tmp/diracos/usr/lib64/firefox/bundled/lib64/libpango-1.0.so.0.4000.4'], {'536e9298b19719476b4ed03d150734da16fc57e17c067f6624b1d751b57ee904', '7b7caade480e9b2379686a2cceee98d8d2a5959d1b388ddc8f5ec2e7a492b017'})
Traceback (most recent call last):
  File "/tmp/bundlelib.py", line 251, in <module>
    main()
  File "/tmp/bundlelib.py", line 245, in main
    manualDependencies=manualDependencies)
  File "/tmp/bundlelib.py", line 224, in _doBundleDIRACOS
    subprocess.check_call(bundleCmd)
  File "/usr/lib64/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/tmp/bundleDiracOS.sh']' returned non-zero exit status 1
Finish: shell
Traceback (most recent call last):
  File "/usr/bin/dos-bundle", line 9, in <module>
    load_entry_point('diracos==1.0.0', 'console_scripts', 'dos-bundle')()
  File "/usr/lib/python2.6/site-packages/diracos/scripts/bundleDiracOS.py", line 17, in main
    diracoslib.bundleDIRACOS(cfg)
  File "/usr/lib/python2.6/site-packages/diracos/diracoslib.py", line 605, in bundleDIRACOS
    subprocess.check_call(bundleCmd)
  File "/usr/lib64/python2.6/subprocess.py", line 505, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['mock', '-r', u'/builds/CLICdp/iLCDirac/DIRACOS/mockConfigs/mock-install-diracos.cfg', '--shell', 'python /tmp/bundlelib.py']' returned non-zero exit status 1
```

**Comment by petricm** [comment]
Since today (02/10/2020) firefox is in requirements
```
DEBUG:root:openldap-servers requires set(['cyrus-sasl-lib', u'openldap-servers', 'nspr', 'glibc', 'tcp_wrappers-libs', 'openssl', 'nss-util', 'openldap', 'portreserve', 'libtool-ltdl', 'firefox', 'nss', 'db4', 'cracklib'])
DEBUG:root:Getting dependencies using ['repoquery', '--queryformat', '"%{name}"', '--requires', '--resolve', '--pkgnarrow=all', u'python-tools']
```
and
```
DEBUG:root:nss-sysinit requires set([u'nss-sysinit', 'sed', 'firefox', 'nspr', 'glibc', 'nss', 'nss-util'])
```
and
```
DEBUG:root:libcurl-devel requires set(['zlib', 'firefox', 'libidn', 'libcom_err', 'openldap', 'nss', 'info', 'libssh2', u'libcurl-devel', 'libcurl', 'glibc', 'nspr', 'automake', 'krb5-libs', 'nss-util', 'autoconf', 'libidn-devel'])
```

and many more

**Comment by petricm** [comment]
```
[root@d960a30e79e0 /]# yum deplist openldap-servers.x86_64 2.4.40-16.el6    
Loaded plugins: fastestmirror, ovl
Finding dependencies: 
Loading mirror speeds from cached hostfile
 * base: linuxsoft.cern.ch
 * epel: linuxsoft.cern.ch
 * extras: linuxsoft.cern.ch
 * updates: linuxsoft.cern.ch
package: openldap-servers.x86_64 2.4.40-16.el6
  dependency: libpthread.so.0(GLIBC_2.3.2)(64bit)
   provider: glibc.x86_64 2.12-1.212.el6
   provider: glibc.x86_64 2.12-1.212.el6_10.3
  dependency: libcrypt.so.1(GLIBC_2.2.5)(64bit)
   provider: glibc.x86_64 2.12-1.212.el6
   provider: glibc.x86_64 2.12-1.212.el6_10.3
  dependency: libc.so.6(GLIBC_2.4)(64bit)
   provider: glibc.x86_64 2.12-1.212.el6
   provider: glibc.x86_64 2.12-1.212.el6_10.3
  dependency: libsmime3.so()(64bit)
   provider: nss.x86_64 3.36.0-8.el6
   provider: firefox.x86_64 78.3.0-1.el6.centos <--------
   provider: nss.x86_64 3.36.0-9.el6_10
   provider: nss.x86_64 3.44.0-7.el6_10
  dependency: openldap = 2.4.40-16.el6
   provider: openldap.i686 2.4.40-16.el6
   provider: openldap.x86_64 2.4.40-16.el6
  dependency: libnss3.so(NSS_3.2)(64bit)
   provider: nss.x86_64 3.36.0-8.el6
   provider: firefox.x86_64 78.3.0-1.el6.centos  <--------
   provider: nss.x86_64 3.36.0-9.el6_10
   provider: nss.x86_64 3.44.0-7.el6_10
  dependency: libssl3.so()(64bit)
   provider: nss.x86_64 3.36.0-8.el6
   provider: firefox.x86_64 78.3.0-1.el6.centos  <--------
   provider: nss.x86_64 3.36.0-9.el6_10
   provider: nss.x86_64 3.44.0-7.el6_10
  dependency: libltdl.so.7()(64bit)
   provider: libtool-ltdl.x86_64 2.2.6-15.5.el6
  dependency: libsasl2.so.2()(64bit)
   provider: cyrus-sasl-lib.x86_64 2.1.23-15.el6_6.2
  dependency: libcrypt.so.1()(64bit)
   provider: glibc.x86_64 2.12-1.212.el6
   provider: glibc.x86_64 2.12-1.212.el6_10.3
  dependency: libpthread.so.0()(64bit)
   provider: glibc.x86_64 2.12-1.212.el6
   provider: glibc.x86_64 2.12-1.212.el6_10.3
  dependency: shadow-utils
   provider: shadow-utils.x86_64 2:4.1.5.1-5.el6
  dependency: libpthread.so.0(GLIBC_2.2.5)(64bit)
   provider: glibc.x86_64 2.12-1.212.el6
   provider: glibc.x86_64 2.12-1.212.el6_10.3
  dependency: libnssutil3.so()(64bit)
   provider: nss-util.x86_64 3.36.0-1.el6
   provider: firefox.x86_64 78.3.0-1.el6.centos  <--------
   provider: nss-util.x86_64 3.44.0-1.el6_10
  dependency: libcrypto.so.10()(64bit)
   provider: openssl.x86_64 1.0.1e-57.el6
   provider: openssl.x86_64 1.0.1e-58.el6_10
  dependency: libldap_r-2.4.so.2()(64bit)
   provider: openldap.x86_64 2.4.40-16.el6
  dependency: libplc4.so()(64bit)
   provider: nspr.x86_64 4.19.0-1.el6
   provider: firefox.x86_64 78.3.0-1.el6.centos  <--------
   provider: nspr.x86_64 4.21.0-1.el6_10
  dependency: libssl.so.10()(64bit)
   provider: openssl.x86_64 1.0.1e-57.el6
   provider: openssl.x86_64 1.0.1e-58.el6_10
  dependency: libdb-4.7.so()(64bit)
   provider: db4.x86_64 4.7.25-22.el6
  dependency: libplds4.so()(64bit)
   provider: nspr.x86_64 4.19.0-1.el6
   provider: firefox.x86_64 78.3.0-1.el6.centos  <--------
   provider: nspr.x86_64 4.21.0-1.el6_10
  dependency: libnss3.so()(64bit)
   provider: nss.x86_64 3.36.0-8.el6
   provider: firefox.x86_64 78.3.0-1.el6.centos  <--------
   provider: nss.x86_64 3.36.0-9.el6_10
   provider: nss.x86_64 3.44.0-7.el6_10
  dependency: libwrap.so.0()(64bit)
   provider: tcp_wrappers-libs.x86_64 7.6-58.el6
  dependency: rtld(GNU_HASH)
   provider: glibc.i686 2.12-1.212.el6
   provider: glibc.x86_64 2.12-1.212.el6
   provider: glibc.i686 2.12-1.212.el6_10.3
   provider: glibc.x86_64 2.12-1.212.el6_10.3
  dependency: libnss3.so(NSS_3.3)(64bit)
   provider: nss.x86_64 3.36.0-8.el6
   provider: firefox.x86_64 78.3.0-1.el6.centos  <--------
   provider: nss.x86_64 3.36.0-9.el6_10
   provider: nss.x86_64 3.44.0-7.el6_10
  dependency: /sbin/runuser
   provider: coreutils.x86_64 8.4-47.el6
  dependency: /bin/sh
   provider: bash.x86_64 4.1.2-48.el6
  dependency: openssl
   provider: openssl.i686 1.0.1e-57.el6
   provider: openssl.x86_64 1.0.1e-57.el6
   provider: openssl.i686 1.0.1e-58.el6_10
   provider: openssl.x86_64 1.0.1e-58.el6_10
  dependency: initscripts
   provider: initscripts.x86_64 9.03.61-1.el6.centos
  dependency: libcrypto.so.10(libcrypto.so.10)(64bit)
   provider: openssl.x86_64 1.0.1e-57.el6
   provider: openssl.x86_64 1.0.1e-58.el6_10
  dependency: libnspr4.so()(64bit)
   provider: nspr.x86_64 4.19.0-1.el6
   provider: firefox.x86_64 78.3.0-1.el6.centos  <--------
   provider: nspr.x86_64 4.21.0-1.el6_10
  dependency: /bin/bash
   provider: bash.x86_64 4.1.2-48.el6
  dependency: portreserve
   provider: portreserve.x86_64 0.0.4-11.el6
  dependency: libresolv.so.2()(64bit)
   provider: glibc.x86_64 2.12-1.212.el6
   provider: glibc.x86_64 2.12-1.212.el6_10.3
  dependency: libcrack.so.2()(64bit)
   provider: cracklib.x86_64 2.8.16-4.el6
  dependency: make
   provider: make.x86_64 1:3.81-23.el6
  dependency: chkconfig
   provider: chkconfig.x86_64 1.3.49.5-1.el6
  dependency: liblber-2.4.so.2()(64bit)
   provider: openldap.x86_64 2.4.40-16.el6
package: openldap-servers.x86_64 2.4.40-16.el6
  dependency: libpthread.so.0(GLIBC_2.3.2)(64bit)
   provider: glibc.x86_64 2.12-1.212.el6
   provider: glibc.x86_64 2.12-1.212.el6_10.3
  dependency: libcrypt.so.1(GLIBC_2.2.5)(64bit)
   provider: glibc.x86_64 2.12-1.212.el6
   provider: glibc.x86_64 2.12-1.212.el6_10.3
  dependency: libc.so.6(GLIBC_2.4)(64bit)
   provider: glibc.x86_64 2.12-1.212.el6
   provider: glibc.x86_64 2.12-1.212.el6_10.3
  dependency: libsmime3.so()(64bit)
   provider: nss.x86_64 3.36.0-8.el6
   provider: firefox.x86_64 78.3.0-1.el6.centos  <--------
   provider: nss.x86_64 3.36.0-9.el6_10
   provider: nss.x86_64 3.44.0-7.el6_10
  dependency: openldap = 2.4.40-16.el6
   provider: openldap.i686 2.4.40-16.el6
   provider: openldap.x86_64 2.4.40-16.el6
  dependency: libnss3.so(NSS_3.2)(64bit)
   provider: nss.x86_64 3.36.0-8.el6
   provider: firefox.x86_64 78.3.0-1.el6.centos  <--------
   provider: nss.x86_64 3.36.0-9.el6_10
   provider: nss.x86_64 3.44.0-7.el6_10
  dependency: libssl3.so()(64bit)
   provider: nss.x86_64 3.36.0-8.el6
   provider: firefox.x86_64 78.3.0-1.el6.centos  <--------
   provider: nss.x86_64 3.36.0-9.el6_10
   provider: nss.x86_64 3.44.0-7.el6_10
  dependency: libltdl.so.7()(64bit)
   provider: libtool-ltdl.x86_64 2.2.6-15.5.el6
  dependency: libsasl2.so.2()(64bit)
   provider: cyrus-sasl-lib.x86_64 2.1.23-15.el6_6.2
  dependency: libcrypt.so.1()(64bit)
   provider: glibc.x86_64 2.12-1.212.el6
   provider: glibc.x86_64 2.12-1.212.el6_10.3
  dependency: libpthread.so.0()(64bit)
   provider: glibc.x86_64 2.12-1.212.el6
   provider: glibc.x86_64 2.12-1.212.el6_10.3
  dependency: shadow-utils
   provider: shadow-utils.x86_64 2:4.1.5.1-5.el6
  dependency: libpthread.so.0(GLIBC_2.2.5)(64bit)
   provider: glibc.x86_64 2.12-1.212.el6
   provider: glibc.x86_64 2.12-1.212.el6_10.3
  dependency: libnssutil3.so()(64bit)
   provider: nss-util.x86_64 3.36.0-1.el6
   provider: firefox.x86_64 78.3.0-1.el6.centos  <--------
   provider: nss-util.x86_64 3.44.0-1.el6_10
  dependency: libcrypto.so.10()(64bit)
   provider: openssl.x86_64 1.0.1e-57.el6
   provider: openssl.x86_64 1.0.1e-58.el6_10
  dependency: libldap_r-2.4.so.2()(64bit)
   provider: openldap.x86_64 2.4.40-16.el6
  dependency: libplc4.so()(64bit)
   provider: nspr.x86_64 4.19.0-1.el6
   provider: firefox.x86_64 78.3.0-1.el6.centos  <--------
   provider: nspr.x86_64 4.21.0-1.el6_10
  dependency: libssl.so.10()(64bit)
   provider: openssl.x86_64 1.0.1e-57.el6
   provider: openssl.x86_64 1.0.1e-58.el6_10
  dependency: libdb-4.7.so()(64bit)
   provider: db4.x86_64 4.7.25-22.el6
  dependency: libplds4.so()(64bit)
   provider: nspr.x86_64 4.19.0-1.el6
   provider: firefox.x86_64 78.3.0-1.el6.centos  <--------
   provider: nspr.x86_64 4.21.0-1.el6_10
  dependency: libnss3.so()(64bit)
   provider: nss.x86_64 3.36.0-8.el6
   provider: firefox.x86_64 78.3.0-1.el6.centos  <--------
   provider: nss.x86_64 3.36.0-9.el6_10
   provider: nss.x86_64 3.44.0-7.el6_10
  dependency: libwrap.so.0()(64bit)
   provider: tcp_wrappers-libs.x86_64 7.6-58.el6
  dependency: rtld(GNU_HASH)
   provider: glibc.i686 2.12-1.212.el6
   provider: glibc.x86_64 2.12-1.212.el6
   provider: glibc.i686 2.12-1.212.el6_10.3
   provider: glibc.x86_64 2.12-1.212.el6_10.3
  dependency: libnss3.so(NSS_3.3)(64bit)
   provider: nss.x86_64 3.36.0-8.el6
   provider: firefox.x86_64 78.3.0-1.el6.centos  <--------
   provider: nss.x86_64 3.36.0-9.el6_10
   provider: nss.x86_64 3.44.0-7.el6_10
  dependency: /sbin/runuser
   provider: coreutils.x86_64 8.4-47.el6
  dependency: /bin/sh
   provider: bash.x86_64 4.1.2-48.el6
  dependency: openssl
   provider: openssl.i686 1.0.1e-57.el6
   provider: openssl.x86_64 1.0.1e-57.el6
   provider: openssl.i686 1.0.1e-58.el6_10
   provider: openssl.x86_64 1.0.1e-58.el6_10
  dependency: initscripts
   provider: initscripts.x86_64 9.03.61-1.el6.centos
  dependency: libcrypto.so.10(libcrypto.so.10)(64bit)
   provider: openssl.x86_64 1.0.1e-57.el6
   provider: openssl.x86_64 1.0.1e-58.el6_10
  dependency: libnspr4.so()(64bit)
   provider: nspr.x86_64 4.19.0-1.el6
   provider: firefox.x86_64 78.3.0-1.el6.centos  <--------
   provider: nspr.x86_64 4.21.0-1.el6_10
  dependency: /bin/bash
   provider: bash.x86_64 4.1.2-48.el6
  dependency: portreserve
   provider: portreserve.x86_64 0.0.4-11.el6
  dependency: libresolv.so.2()(64bit)
   provider: glibc.x86_64 2.12-1.212.el6
   provider: glibc.x86_64 2.12-1.212.el6_10.3
  dependency: libcrack.so.2()(64bit)
   provider: cracklib.x86_64 2.8.16-4.el6
  dependency: make
   provider: make.x86_64 1:3.81-23.el6
  dependency: chkconfig
   provider: chkconfig.x86_64 1.3.49.5-1.el6
  dependency: liblber-2.4.so.2()(64bit)
   provider: openldap.x86_64 2.4.40-16.el6
```

**Comment by petricm** [comment]
I don't really get it here for the clients there is not firefox in the deps
https://centos.pkgs.org/6/centos-x86_64/openldap-clients-2.4.40-16.el6.x86_64.rpm.html
