### ISSUE TITLE
yum utils version mismatch

### ISSUE THREAD

**Issue by petricm** [DIRACGrid/DIRACOS#23]
yum-utils-1.1.30-41(base) vs yum-utils-1.1.30-40(lhcb)
```
[root@90c8bd9bc220 ~]# dos-bundle DIRACOS/config/diracos.json
INFO:root:Bootstraping packaging of diracos
INFO: mock.py version 1.3.5 starting (python version = 2.6.6)...
Start: init plugins
INFO: selinux disabled
Finish: init plugins
Start: run
Start: chroot init
INFO: calling preinit hooks
INFO: enabled root cache
INFO: enabled yum cache
Start: cleaning yum metadata
Finish: cleaning yum metadata
INFO: enabled HW Info plugin
Start: yum install
Error: Package: yum-utils-1.1.30-41.el6.noarch (base)
           Requires: python(abi) = 2.6
           Available: python-2.7.13-2.el6.i686 (local-py2.7)
               python(abi) = 2.7
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
ERROR: Command failed: 
 # /usr/bin/yum --installroot /var/lib/mock/epel-6-x86_64-install/root/ install @buildsys-build yum yum-utils python-devel xz-devel gcc git
Error: Package: yum-utils-1.1.30-41.el6.noarch (base)
           Requires: python(abi) = 2.6
           Available: python-2.7.13-2.el6.i686 (local-py2.7)
               python(abi) = 2.7
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

Traceback (most recent call last):
  File "/usr/bin/dos-bundle", line 9, in <module>
    load_entry_point('diracos==0.0.1', 'console_scripts', 'dos-bundle')()
  File "/usr/lib/python2.6/site-packages/scripts/bundleDiracOS.py", line 17, in main
    diracoslib.bundleDIRACOS(cfg)
  File "/usr/lib/python2.6/site-packages/diracos/diracoslib.py", line 609, in bundleDIRACOS
    subprocess.check_call(bundleCmd)
  File "/usr/lib64/python2.6/subprocess.py", line 505, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['mock', '-r', u'/root/DIRACOS/mockConfigs/mock-install-diracos.cfg', '--shell', 'python /tmp/bundlelib.py']' returned non-zero exit status 30
```

**Comment by chaen** [comment]
In https://github.com/DIRACGrid/DIRACOS/pull/25
