### ISSUE TITLE
Add oracle

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRACOS#34]
do what is said in the title

**Comment by chaen** [comment]
The version we have now  `5.1`  does not work without an installation of oracle:

```
(pipDirac) <mock-chroot> sh-4.1# pip install cx_Oracle==5.1.3
Collecting cx_Oracle==5.1.3
  Downloading https://files.pythonhosted.org/packages/be/25/afc07a79ed268f6ab2e8959cfcff997504ce09500b881a1d93f92904762e/cx_Oracle-5.1.3.tar.gz (104kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-4FBxLS/cx-Oracle/setup.py", line 135, in <module>
        raise DistutilsSetupError("cannot locate an Oracle software " \
    distutils.errors.DistutilsSetupError: cannot locate an Oracle software installation
```

However the latest one does:

```
pipDirac) <mock-chroot> sh-4.1# pip install cx_Oracle
Collecting cx_Oracle
  Downloading https://files.pythonhosted.org/packages/3b/09/6b10675a6db7c7da1b8d23225f0a95b2a45248c56a1e8f711d59809278d3/cx_Oracle-6.4.1-cp27-cp27mu-manylinux1_x86_64.whl (590kB)
Installing collected packages: cx-Oracle
Successfully installed cx-Oracle-6.4.1
```

@zmathe to test if this is compatible with the CERN installation of Oracle

**Comment by zmathe** [comment]
I installed diracos to LHCb certification machine.
pip install cx_Oracle
cx_Oracle 7.0.0 is installed. I do not see any issue....

**Comment by chaen** [comment]
Added
