### ISSUE TITLE
virtualenv does not work

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRACOS#35]
Initial issue is that the shebang of virtualenv is 
```
DIRAC-PROD>virtualenv /tmp/toto
/usr/bin/env: python2.7 -s: No such file or directory
```
The problem is this line. Only one argument is passed to the command in the shebang (https://www.in-ulm.de/~mascheck/various/shebang/)

`#!/usr/bin/env python2.7 -s`

This is done by the diracos bundle script, originally it is `#!/usr/bin/python2.7 -s`

The `-s`confuses things

But even when this is fixed, it does not work

```
DIRAC-PROD>virtualenv /tmp/toto
Using real prefix '/usr'
New python executable in /tmp/toto/bin/python2.7
Also creating executable in /tmp/toto/bin/python
Installing setuptools, pip, wheel...
  Complete output from command /tmp/toto/bin/python2.7 - setuptools pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
ImportError: No module named pkgutil
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/opt/dirac/diracos/usr/bin/virtualenv", line 3, in <module>
    virtualenv.main()
  File "/opt/dirac/diracos/usr/lib/python2.7/site-packages/virtualenv.py", line 711, in main
    symlink=options.symlink)
  File "/opt/dirac/diracos/usr/lib/python2.7/site-packages/virtualenv.py", line 944, in create_environment
    download=download,
  File "/opt/dirac/diracos/usr/lib/python2.7/site-packages/virtualenv.py", line 900, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/opt/dirac/diracos/usr/lib/python2.7/site-packages/virtualenv.py", line 795, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /tmp/toto/bin/python2.7 - setuptools pip wheel failed with error code 1
```

**Comment by fstagni** [comment]
I guess this (and maybe other issues here in DIRACOS...) can be closed with a "won't do".

**Comment by petricm** [comment]
will not be fixed before end of life of DIRACOS
