### ISSUE TITLE
Issues with vanilla container

### ISSUE THREAD

**Issue by petricm** [DIRACGrid/DIRACOS#45]
If you want to use DIRACOS in the vanilla cern/slc6-base container you would execute
```
curl -O http://diracos.web.cern.ch/diracos/master/diracos-master.tar.gz
curl -O https://raw.githubusercontent.com/DIRACGrid/DIRACOS/master/tests/integration/test_import.py
yum install tar -y
tar xf diracos-master.tar.gz -C /tmp
export DIRACOS=/tmp/diracos
source $DIRACOS/diracosrc
```

then if you run the test `pytest test_import.py` it fails with
```
# pytest test_import.py 
=============================================================== test session starts ===============================================================
platform linux2 -- Python 2.7.13, pytest-3.9.2, py-1.7.0, pluggy-0.8.0
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/.hypothesis/examples')
rootdir: /, inifile:
plugins: cov-2.6.0, hypothesis-3.79.3
collected 109 items                                                                                                                               

test_import.py ..............................F.............................s................................................                [100%]

==================================================================== FAILURES =====================================================================
________________________________________________________________ test_module[git] _________________________________________________________________

moduleName = 'git'

    @parametrize('moduleName', moduleNames)
    def test_module(moduleName):
      """ Try to import a module and check whether it is located in DIRACOS.
    
          Modules that are in the ALLOWED_TO_FAIL list are shown as skipped and generate a warning
    
          Modules that require graphic libraries on the system (GRAPHIC_MODULES) are skipped on container
      """
    
      try:
        module = __import__(moduleName)
    
        # Test whether it is correctly imported from DIRACOS
    
        try:
          modulePath = module.__file__
          # return true, if the common prefix of both is equal to directory
          # e.g. /a/b/c/d.rst and directory is /a/b, the common prefix is /a/b
          assert os.path.commonprefix([modulePath, diracosPath]) == diracosPath, \
              "ERROR %s not from DIRACOS: %s" % (moduleName, modulePath)
    
        # builtin modules like sys have no path
        except AttributeError as e:
          print "WARNING no path for %s" % moduleName
    
      except ImportError as e:
        msg = "could not import %s: %s" % (moduleName, repr(e))
        print traceback.print_exc()
    
        if moduleName in ALLOWED_TO_FAIL:
          warnings.warn(msg)
          pytest.skip("WARN: " + msg)
        elif moduleName in GRAPHIC_MODULES:
          warnings.warn(msg + "(Possibly due to system graphic libraries not present)")
          pytest.skip("WARN: " + msg + "(Possibly due to system graphic libraries not present)")
        else:
>         pytest.fail("ERROR: " + msg)
E         Failed: ERROR: could not import git: ImportError('Failed to initialize: Bad git executable.\nThe git executable must be specified in one of the following ways:\n    - be included in your $PATH\n    - be set via $GIT_PYTHON_GIT_EXECUTABLE\n    - explicitly set via git.refresh()\n\nAll git commands will error until this is rectified.\n\nThis initial warning can be silenced or aggravated in the future by setting the\n$GIT_PYTHON_REFRESH environment variable. Use one of the following values:\n    - quiet|q|silence|s|none|n|0: for no warning or exception\n    - warn|w|warning|1: for a printed warning\n    - error|e|raise|r|2: for a raised exception\n\nExample:\n    export GIT_PYTHON_REFRESH=quiet\n',)

test_import.py:238: Failed
-------------------------------------------------------------- Captured stdout call ---------------------------------------------------------------
None
-------------------------------------------------------------- Captured stderr call ---------------------------------------------------------------
Traceback (most recent call last):
  File "/test_import.py", line 212, in test_module
    module = __import__(moduleName)
  File "/tmp/diracos/usr/lib64/python2.7/site-packages/git/__init__.py", line 85, in <module>
    raise ImportError('Failed to initialize: {0}'.format(exc))
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

================================================= 1 failed, 107 passed, 1 skipped in 2.54 seconds =================================================
```

**Comment by chaen** [comment]
In https://github.com/DIRACGrid/DIRACOS/pull/48
